name: Lint OpenAPI spec on Pull Requests

on:
  pull_request:

jobs:
  lint:
    name: Lint OpenAPI
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run Spectral
        uses: stoplightio/spectral-action@v0.8.11
        with:
          file_glob: 'src/main/resources/openapi/*.openapi.yaml'
          spectral_ruleset: 'https://raw.githubusercontent.com/SchwarzIT/api-linter-rules/main/spectral-api.yml'
